updating workflow

diff --git a/.github/workflows/generate.yaml b/.github/workflows/generate.yaml
--- a/.github/workflows/generate.yaml
+++ b/.github/workflows/generate.yaml
@@ -48,7 +48,7 @@ jobs:
       - name: Show one of the generated files
         run: |
           echo "📄 Showing content of a sample file:"
-          cat */*redb*/redb-*.yaml || echo "File not found!"
+          cat redb/test-redb/redb*.yaml || echo "File not found!"
           
 
       - name: Commit & Push Changes
